export const types = {
    ADD_RECENT_GAMES: 'ADD_RECENT_GAMES',
    ADD_DETAIL_GAME: 'ADD_DETAIL_GAME',
    REMOVE_DETAIL_GAME: 'REMOVE_DETAIL_GAME',
    ADD_SEARCH_LIST: 'ADD_SEARCH_LIST',
    RESET_GAMES:'RESET_GAMES'
}